# Estos son los botones de patrocinio soportados
github: # choco-latito29 (Si tuvieras GitHub Sponsors activado)
custom: [
    "https://paypal.me/TU_USUARIO_CHOCO", # 👈 Tu PayPal
    "https://paypal.me/ElAldaOficial", # 👈 PayPal de ElAlda (Reemplaza con el real si lo tienes)
    "https://kick.com/elaldass",
    "https://www.youtube.com/@elalda",
  ]
