name: Production Release Builder

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Production Zip
        run: zip -r Production-Build.zip . -x "*.git*" "*node_modules*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Production-Build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
